### ISSUE TITLE
Failing CopyBaseImages step doesn't fail the PreBuildValidation pipeline stage

### ISSUE THREAD

**Issue by lbussell** [dotnet/docker-tools#1256]
See the output in this public PR validation pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=656237&view=logs&j=1a3858d4-df16-5910-9f2f-b79bed34300b&t=753b3247-b9b0-566e-d813-4e57c0e7e6de&l=108

Even though the CopyBaseImages step has failed with an exception, the pipeline doesn't fail on the PreBuildValidation stage.

**Comment by mthalman** [comment]
That's intentional: https://github.com/dotnet/docker-tools/blob/8fa03e26afbf7676865f2335c0b2f78baf5dbfe9/eng/common/templates/jobs/copy-base-images.yml#L18

It's to ensure our build won't be blocked by unavailability of the base images (e.g. Docker Hub registry down or something). But yes, it can be a problem for legitimate issues on our side.

**Comment by lbussell** [comment]
OK. There's probably some solution we could make where an exception in ImageBuilder fails but an exception from PowerShell (for example) throws a warning and skips the rest of the stage. But it's not a pressing issue so closing as not planned unless we start having more issues.
