### ISSUE TITLE
Add data-root check for Docker build agent validation

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#179]
By default, the Docker daemon config has it's data-root empty which means it defaults to the C: drive.  But the build agents have their data drive at E: with much more capacity.  The pipeline that validates the build agent should check that the data-root is set appropriately.

**Comment by MichaelSimons** [comment]
When working on this, keep in mind the current pipeline that validates the build agent is for the arm scenarios whereas this issue is for any AzDO build agent in the dotnet docker pools.  This check would not be appropriate to run on the remote Docker daemons as they are not configured with the data drive.

**Comment by MichaelSimons** [comment]
This is something that DDFUN should be responsible as they are the owners of configuring the machines.

cc @ilyas1974
