### ISSUE TITLE
Define a pipeline that can prepopulate Docker cache with base Windows images

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#481]
When new Windows base images are released, the build jobs for the Windows-based .NET images end up taking longer to execute because they need to pull down the new base image.  This is particularly true for the Server Core images because of their large size.  Once they're on the build agent, they are cached across builds because the cleanup logic explicitly omits removing tagged Windows images.

Now that the final versions of the Windows images are available internally prior to release, it is possible to make use of them and pull them on our build agents prior to the release build in order to prepopulate the Docker cache.  This will make the actual release build run faster (~10-15 mins for Server Core) because it won't need to pull the base image.

**Comment by MichaelSimons** [comment]
The infrastructure changes to support this would not be trivial.  The logic would need to pull the internal images and then have a way to flag them so that the normal cleanup logic doesn't delete them in case a normal build happens before the release.

After discussing this we've decided to hold off on implementing this as the ROI seems limited.
