### ISSUE TITLE
Define `latest` tag for Image Builder

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#720]
Currently we don't publish a `latest` tag for `mcr.microsoft.com/dotnet-buildtools/image-builder`.  The only way to pull Image Builder is to reference one of the unique tags that are produced for each build.

This complicates the ability to pre-pull Image Builder on from the VM images defined for the scale set agents (https://github.com/dotnet/docker-tools/issues/532).  Ideally we'd have those VM images contain the latest Docker images for Windows Server Core, Nano Server, and Image Builder.  For Windows Server Core and Nano Server, it's easy to configure this because they have floating tags that get updated to point to the latest patch release.  But for Image Builder, it would require updating the script to point to the latest unique tag value.  That's not maintainable.  Instead, it'd be better to simply have the script reference `mcr.microsoft.com/dotnet-buildtools/image-builder:latest` and get the latest version of Image Builder.

**Comment by MichaelSimons** [comment]
Because the frequency on which image-builder changes, caching the image-builder in the image won't provide value.  The out of date image would get removed with the cleanup logic which would add overhead.  We are going to hold-off on any changes here until we get the scale set agents in place to see if it is needed.  We can re-open this if necessary.
